---
- name: Network Getting Started First Playbook for configuring the Cisco device
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false

  tasks:
    - name: Get config for IOS devices
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Execute show command to test enable password
      ios_command:
        commands:
          - show running-config
        #  - show version
      register: saved_facts

    - debug:
        var: saved_facts

    - debug:
        msg:
        - "{{saved_facts['ansible_facts']['ansible_net_hostname']}}"


