---
- name: IOS Command from file demo
  hosts: switches
  gather_facts: no
  tasks:
    # - name: Access port configuration on cisco switch
    #   cisco.ios.ios_l2_interfaces:
    #     config:
    #       - name: GigabitEthernet0/2
    #         mode: access
    #         access:
    #           vlan: 10
    #     state: merged
    
    - name: Single vlan creation of switch
      cisco.ios.ios_vlans:
        config:
          - name: vlan_10
            vlan_id: 10
            state: active
            shutdown: disabled
          - name: vlan_11
            vlan_id: 11
            state: active
            shutdown: disabled
          - name: vlan_12
            vlan_id: 12
            state: active
            shutdown: disabled
          - name: vlan_13
            vlan_id: 13
            state: active
            shutdown: disabled
        state: merged
    
    - name: Show VLAN configuration
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: show_vlans
    
    - name: Pretty print VLAN data
      debug:
        var: show_vlans
    
    - name: making interface as dot1q tagged
      cisco.ios.ios_config:
        parents: interface GigabitEthernet0/2
        lines:
          - switchport trunk encapsulation dot1q
        diff_against: startup
    
    - name: trunk configuration on the switches
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet0/2
            mode: trunk
            trunk:
              allowed_vlans: 10-15
              native_vlan: 1
              encapsulation: dot1q
        state: merged
        diff_against: startup